config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      sessions: "users/sessions",
      invitations: 'users/invitations'
    },
    :path => '',
    path_names: { sign_in: 'login', sign_out: 'logout' }

  ActiveAdmin.routes(self)

  namespace :admin do
    %w(dashboard datapoint dataset widget).each do |model|
      resources model.to_sym do
        resources :audits
      end
    end
  end

  constraints CanAccessFlipperUI do
    mount Flipper::UI.app($flipper) => '/flipper'
  end

  resource :user, :only => 'show' do
    resources :tokens, :only => 'create'
  end

  namespace :users do
    resources :shared_secrets, only: [:new, :create, :index] do
      collection do
        get :code
        get :done
      end
    end
    match 'shared_secret', to: 'shared_secrets#destroy', via: :delete
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      post 'initialise-dashboard', to: 'dashboards#create_full'
      resources :dashboards do
        post 'initialise-widget', to: 'widgets#create_full'
        post 'initialise-kpis', to: 'widgets#create_kpis'
        resources :widgets
      end
      resources :datasets
      resources :organisations, only: [:index]
      resources :features, only: [:index]
      resources :widgets, only: [:create] do
        get 'slices/:period/:period_start', to: 'slices#show'
        post 'slices/:period/:period_start', to: 'slices#create'
        patch 'slices/:period/:period_start', to: 'slices#update'
      end
    end
  end

  get '/editor(*path)', :to => 'editor#index', :as => 'editor'

  get root :to => 'dashboards#index'

  resources :dashboards, only: [:show] do
    member do
      get :export
    end
  end

  get 'feedback', :to => 'feedback#index'

  get '/index.html', :to => redirect('/')

  get '/copyright', :to => 'about#copyright'
  get '/api', :to => 'about#api'

  get '*unmatched_route', to: 'application#not_found'
end

app/models/user.rb
class User < ApplicationRecord
  devise :invitable, :two_factor_authenticatable, :database_authenticatable,
    :confirmable, :lockable, :recoverable, :rememberable, :timeoutable,
    :trackable, :validatable

  has_one_time_password(encrypted: true)

  has_many :tokens do
    def expire
      update(:expired_at => Time.zone.now)
    end
  end

  belongs_to :organisation

  has_many :permissions, dependent: :destroy
  has_many :dashboards, through: :permissions, source: :resource,
    source_type: 'Dashboard'
  has_many :widgets, through: :dashboards
  has_many :organisations, through: :dashboards

  def self.by_email
    order(:email => 'ASC')
  end

  def self.authenticate!(token)
    Token.authenticate!(token).user
  end

  def expire_session_tokens
    tokens.session.expire
  end

  def generate_api_token!
    tokens.create!(:session => false)
  end

  def generate_session_token!
    expire_session_tokens
    tokens.create!(:session => true)
  end

  def token
    tokens.active.first
  end

  def api_token
    tokens.api.active.first
  end

  def session_token
    tokens.session.active.first
  end

  def to_s
    email
  end

  def datasets
    dashboards.collect {|dashboard|
      dashboard.datasets.to_a
    }.flatten.uniq
  end

  def need_two_factor_authentication?(_request)
    $flipper[:two_factor].enabled?
  end

  def send_two_factor_authentication_code(code)
    # Send code via SMS, etc.
  end
end

app/controllers/users/invitations_controller.rb
class Users::InvitationsController < Devise::InvitationsController
  before_action :set_organisations, only: [:new, :create]

  def invite_resource
    @dashboards = if params['user']['dashboard_ids']
      params['user']['dashboard_ids'].reject(&:empty?).collect do |id|
        Dashboard.find(id)
      end
    else
      []
    end

    super do |resource|
      dashboard_orgs = @dashboards.collect {|d| d.organisation }.uniq

      case dashboard_orgs.count
      when 0
        resource.errors.add :dashboards, 'missing'
      when 1
        resource.organisation = dashboard_orgs.first
        resource.dashboards = @dashboards
      else
        resource.errors.add :dashboards, 'should only be chosen from within a single organisation'
      end
    end
  end

  private

  def after_accept_path_for(resource)
    if $flipper[:two_factor].enabled? && resource.otp_secret_key.blank?
      users_shared_secrets_path
    else
      super
    end
  end

  def set_organisations
    if current_user.admin?
      @show_dashboards = true

      @organisations = Organisation.all.select do |org|
        org.dashboards.any?
      end
    else
      @organisations = [current_user.organisation]
      @show_dashboards = current_user.organisation.dashboards.count != 1
    end

    @select_size = @organisations.inject(0) do |sum, org|
      sum + 1 + org.dashboards.count
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  skip_before_action :require_no_authentication, only: [:create]

  layout 'devise'

  # GET /resource/login
  def new
    super
  end

  # POST /resource/login
  def create
    super
  end

  # DELETE /resource/logout
  def destroy
    super
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/shared_secrets_controller.rb
class Users::SharedSecretsController < ApplicationController
  layout 'devise'

  before_action :ensure_secret_exists, only: [:new, :code]
  before_action :protect_from_abuse, except: [:done]

  def create
    if secret.present?
      if authenticate_code secret, params[:code]
        current_user.update_attribute :otp_secret_key, secret
        session.delete :setup_totp
        warden.session(:user)[TwoFactorAuthentication::NEED_AUTHENTICATION] = false
        redirect_to done_users_shared_secrets_path
      else
        current_user.increment! :second_factor_attempts_count
        @form_error = 'Your code didn\'t work. Please try again.'
        render :new
      end
    else
      redirect_to new_users_shared_secret_path
    end
  end

  def code
    uri = "otpauth://totp/#{current_user.email}?secret=#{secret}&issuer=#{issuer}"

    respond_to do |format|
      format.html
      format.png { render qrcode: uri, unit: 6 }
    end
  end

  def destroy
    session.delete :setup_totp
    redirect_to users_shared_secrets_path
  end

  def index
  end

  def new
  end

  def done
  end

  private

  def authenticate_code(key, code)
    code.present? && key.present? && ROTP::TOTP.new(key).now == code
  end

  def secret
    @secret ||= session[:setup_totp]
  end

  def secret=(value)
    session[:setup_totp] = value
  end

  def ensure_secret_exists
    self.secret = current_user.generate_totp_secret unless secret.present?
  end

  def issuer
    if Rails.env.development?
      'localhost'
    else
      ENV['APP_DOMAIN']
    end
  end

  def devise_controller?
    true
  end

  def protect_from_abuse
    if current_user.otp_secret_key.present?
      head 403
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  layout 'editor'

  before_action :authenticate_user!

end

app/views/users/show.html.erb
<% content_for :title, 'Account Details' %>

<div id="user_show">
      <div class="page page-users">
          <div class="page__header">
              <div class="container">
                  <div class="row">
                      <div class="col-xs-12 col-lg-8">
                          <div class="breadcrumbs" aria-label="breadcrumb">
                              <ol>
                                  <li>Account Details</li>
                              </ol>
                          </div>
                          <h1 class="h3">Account Details</h1></div>
                  </div>
              </div>
          </div>
          <div class="container">
              <div class="page__body">
                  <div class="row">
                      <div class="col-xs-12 col-lg-8">
                          <section class="users-list__item">
                              <article>
                                  <% if flash[:api_token] -%>
                                    <div class="UIK-alert alert alert-success" role="alert">
                                      <div class="alert__icon"><i>success</i></div>
                                      <div class="alert__text">
                                        <span className="heading-text">New API Token</span>
                                        <p><strong><%= flash[:api_token] %></strong></p>
                                        <p>Make sure to copy your new api token now. You won’t be able to see it again!</p>
                                      </div>
                                    </div>
                                  <% end -%>
                                  <table class="table">
                                    <tr> <th>Email</th><td><%= current_user.email %> </td></tr>
                                    <tr> <th>Signed in</th><td><%= pluralize(current_user.sign_in_count, 'time') %> </td></tr>
                                    <tr> <th>Signed in at</th><td><%= current_user.current_sign_in_at.to_s(:long) %> </td></tr>
                                    <tr> <th>Last signed in at</th><td><%= current_user.last_sign_in_at.to_s(:long) %> </td></tr>
                                    <tr> <th>Last signed in from IP</th><td><%= current_user.last_sign_in_ip %> </td></tr>
                                  </table>
                              </article>
                          </section>
                          <section class="users-list__item">
                            <h3>API Tokens</h3>
                            <% if current_user.tokens.api.any? %>
                              <table class="table">
                                <thead>
                                  <tr>
                                    <th>Token</th>
                                    <th>Created At</th>
                                    <th>Active</th>
                                    <th></th>
                                  </tr>
                                </thead>
                                <% current_user.tokens.api.decorate.each do |token| %>
                                  <tr>
                                    <td><%= token.to_short_s %></td>
                                    <td><%= token.created_at.to_s(:long) %></td>
                                    <td><%= token.active? %> </td>
                                  </tr>
                                <% end %>
                              </table>
                            <% end %>
                            <p>
                              <%= button_to('Generate API Token', user_tokens_path, :class => 'UIK-button btn btn-primary') %>
                            </p>
                          </section>
                      </div>
                  </div>
              </div>
          </div>
      </div>
</div>