config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      sessions: "users/sessions",
      invitations: 'users/invitations'
    },
    :path => '',
    path_names: { sign_in: 'login', sign_out: 'logout' }

  ActiveAdmin.routes(self)

  namespace :admin do
    %w(dashboard datapoint dataset widget).each do |model|
      resources model.to_sym do
        resources :audits
      end
    end
  end

  constraints CanAccessFlipperUI do
    mount Flipper::UI.app($flipper) => '/flipper'
  end

  resource :user, :only => 'show' do
    resources :tokens, :only => 'create'
  end

  namespace :users do
    resources :shared_secrets, only: [:new, :create, :index] do
      collection do
        get :code
        get :done
      end
    end
    match 'shared_secret', to: 'shared_secrets#destroy', via: :delete
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      post 'initialise-dashboard', to: 'dashboards#create_full'
      resources :dashboards do
        post 'initialise-widget', to: 'widgets#create_full'
        post 'initialise-kpis', to: 'widgets#create_kpis'
        resources :widgets
      end
      resources :datasets
      resources :organisations, only: [:index]
      resources :features, only: [:index]
      resources :widgets, only: [:create] do
        get 'slices/:period/:period_start', to: 'slices#show'
        post 'slices/:period/:period_start', to: 'slices#create'
        patch 'slices/:period/:period_start', to: 'slices#update'
      end
    end
  end

  get '/editor(*path)', :to => 'editor#index', :as => 'editor'

  get root :to => 'dashboards#index'

  resources :dashboards, only: [:show] do
    member do
      get :export
    end
  end

  get 'feedback', :to => 'feedback#index'

  get '/index.html', :to => redirect('/')

  get '/copyright', :to => 'about#copyright'
  get '/api', :to => 'about#api'

  get '*unmatched_route', to: 'application#not_found'
end

app/models/dashboard.rb
class Dashboard < ApplicationRecord
  include Nameable
  audited
  has_associated_audits

  belongs_to :organisation
  has_many :widgets
  has_many :btl_widgets, -> { btl }, class_name: 'Widget'
  has_many :data_tables
  has_many :datasets, through: :data_tables
  has_many :permissions, as: :resource, dependent: :destroy
  has_many :users, through: :permissions

  accepts_nested_attributes_for :widgets

  validates :name, :description, :target_users, :presence => true
  validates :url, :url => true, :allow_nil => true

  serialize :notes, JSON

  def self.published
    where('published_at <= NOW()')
  end

  def published?
    published_at.present? && published_at <= Time.now
  end

  def self.available(password_param)
    if password_param && password_param.length <= 10 && password_param.match(/\A[a-zA-Z0-9]*\z/)
      return where("password = \'\' OR password = \'#{password_param}\'")
    end

    return where("password = \'\'")
  end

  def hero
    widgets.hero.first
  end

  def rows
    @rows ||= widgets.without_hero.by_row.by_pos.inject([]){ | a, w|
      a[w.row] = [] unless a[w.row]
      a[w.row] << w
      a
    }.compact
  end

  def first_row
    rows.first
  end

  def remaining_rows
    if widgets.kpis.any?
      rows.drop(1)
    else
      rows
    end
  end

  def to_param
    @slug ||= "#{id}-#{name.parameterize}"
  end

  def last_updated_at
    widgets.by_last_updated&.last&.last_updated_at
  end
end

app/controllers/api/v1/dashboards_controller.rb
class Api::V1::DashboardsController < Api::V1::ApiController
  attr_reader :dashboard

  before_action :find_dashboard, :only => [:show, :update]

  def index
    dashboards = current_user.dashboards.by_name.all
    render :json => dashboards.to_json
  end

  def create
    dashboard = Dashboard.new dashboard_params
    dashboard.published_at = Time.now
    dashboard.save!

    render :json => dashboard.to_json
  end

  # Creates a dashboard with 4 KPI widgets, datasets
  def create_full
    dashboard = Dashboard.new dashboard_params
    dashboard.notes = params[:notes].as_json
    dashboard.published_at = Time.now
    dashboard.save!

    data_table = DataTable.create({
      :dashboard_id => dashboard.id,
      :options => {
        :period => 'month',
        :slice_aggregation => 'mean'
      }
    })

    widget0 = Widget.create({
      :dashboard_id => dashboard.id,
      :data_table_id => data_table.id,
      :name => 'Kpis',
      :options => {},
      :description => 'Descrip',
      :row => 0,
      :pos => 0,
      :type => 'full',
      :size => 'extra-large',
      :units => 'n',
      :is_hero => true
    })

    widget1 = Widget.create({
      :dashboard_id => dashboard.id,
      :data_table_id => data_table.id,
      :name => 'User satisfaction',
      :options => {},
      :description => 'Overall satisfaction score includes all ratings weighted from 100% for very satisfied to 0% for very dissatisfied',
      :row => 1,
      :pos => 0,
      :type => 'kpi-sparkline',
      :size => 'extra-small',
      :units => '%'
    })

    widget2 = Widget.create({
      :dashboard_id => dashboard.id,
      :data_table_id => data_table.id,
      :name => 'Cost per transaction',
      :options => {},
      :description => 'Desc',
      :row => 1,
      :pos => 1,
      :type => 'kpi-sparkline',
      :size => 'extra-small',
      :units => '$'
    })

    widget3 = Widget.create({
      :dashboard_id => dashboard.id,
      :data_table_id => data_table.id,
      :name => 'Digital take-up',
      :options => {},
      :description => 'Desc',
      :row => 1,
      :pos => 2,
      :type => 'kpi-sparkline',
      :size => 'extra-small',
      :units => '%'
    })

    widget4 = Widget.create({
      :dashboard_id => dashboard.id,
      :data_table_id => data_table.id,
      :name => 'Completion rate',
      :options => {},
      :description => 'Desc',
      :row => 1,
      :pos => 3,
      :type => 'kpi-sparkline',
      :size => 'extra-small',
      :units => '%'
    })

    dataset1 = Dataset.create({
      :name => 'User satisfaction',
      :label => 'User satisfaction',
      :units => '%',
      :notes => 'User satisfaction measures the percentage of users who responded "satisfied" or "very satisfied" in our feedback survey. This figure is not yet statistically significant because of the low number of feedback responses from August 2016 onwards. In addition, we have no data for the months of May, June and July 2016 because no users provided feedback. We are determining the best way to encourage more feedback from our users.',
      :period => 'month',
      :options => {}
    })

    dataset2 = Dataset.create({
      :name => 'Cost per transaction',
      :label => 'Cost per transaction',
      :units => '$',
      :notes => 'This data is currently unavailable due to....',
      :period => 'month',
      :options => {}
    })

    dataset3 = Dataset.create({
      :name => 'Digital take-up',
      :label => 'Digital take-up',
      :units => '%',
      :notes => 'The percentage of visitors to the business.gov.au',
      :period => 'month',
      :options => {}
    })

    dataset4 = Dataset.create({
      :name => 'Completion rate',
      :label => 'Completion rate',
      :units => '%',
      :notes => 'The percentage of users who successfully generate a result after starting the tool. This is calculated by dividing the total number of successfully completed transactions by the total number of started transactions.',
      :period => 'month',
      :options => {}
    })

    DataTableDataset.create({
      :dataset_id => dataset1.id,
      :data_table_id => data_table.id
    })

    DataTableDataset.create({
      :dataset_id => dataset2.id,
      :data_table_id => data_table.id
    })

    DataTableDataset.create({
      :dataset_id => dataset3.id,
      :data_table_id => data_table.id
    })

    DataTableDataset.create({
      :dataset_id => dataset4.id,
      :data_table_id => data_table.id
    })

    DatasetWidget.create({
      :dataset_id => dataset1.id,
      :widget_id => widget1.id,
      :order_num => 0
    })

    DatasetWidget.create({
      :dataset_id => dataset2.id,
      :widget_id => widget2.id,
      :order_num => 1
    })

    DatasetWidget.create({
      :dataset_id => dataset3.id,
      :widget_id => widget3.id,
      :order_num => 2
    })

    DatasetWidget.create({
      :dataset_id => dataset4.id,
      :widget_id => widget4.id,
      :order_num => 3
    })

    DatasetWidget.create({
      :dataset_id => dataset1.id,
      :widget_id => widget0.id,
      :order_num => 0
    })

    DatasetWidget.create({
      :dataset_id => dataset2.id,
      :widget_id => widget0.id,
      :order_num => 1
    })

    DatasetWidget.create({
      :dataset_id => dataset3.id,
      :widget_id => widget0.id,
      :order_num => 2
    })

    DatasetWidget.create({
      :dataset_id => dataset4.id,
      :widget_id => widget0.id,
      :order_num => 3
    })

    DataRow.create({
      :data_table_id => data_table.id,
      :row_date => "#{params[:periodYear]}-#{params[:periodMonth]}-01",
      :data => {
        :values => {
          dataset1.id => params[:userSatisfaction].empty? ? nil : params[:userSatisfaction],
          dataset2.id => params[:costPerTransaction].empty? ? nil : params[:costPerTransaction],
          dataset3.id => params[:digitalTakeup].empty? ? nil : params[:digitalTakeup],
          dataset4.id => params[:completionRate].empty? ? nil : params[:completionRate]
        }
      }
    })

    Permission.create({
      :resource_type => 'Dashboard',
      :resource_id => dashboard.id,
      :user_id => current_user.id
    })

    render :json => dashboard.to_json
  end

  def show
    render :json => dashboard.to_json
  end

  def update
    with_invalid_record_handler do
      invalidate_dashboards dashboard
      dashboard.update_attributes!(data)
      render :json => dashboard.to_json, :status => :ok
    end
  end

  private

  def find_dashboard
    begin
      @dashboard = current_user.dashboards.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      head :not_found
    end
  end

  def data
    params.permit(:name, :description, :target_users, :notes, :url, :published_at)
  end

  def dashboard_params
    params.permit(:name, :description, :target_users, :organisation_id, :url, :notes, :published_at)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  caches_page :show, :index

  attr_reader :dashboards, :dashboard, :widgets
  helper_method :dashboards, :dashboard

  def index
    @dashboards = Dashboard.available(params[:password]).published.by_name.all.decorate
  end

  def show
    @dashboard = Dashboard.available(params[:password]).published.find(params[:id]).decorate
    @title = @dashboard.name
    @description = @dashboard.name

    @slices = @dashboard.widgets.select {|widget|
      widget.has_data?
    }.collect {|widget|
      # widget.data_table.decorate.slices(widget, limit: 13)
      widget.data_table.slices(widget, limit: 13) # Jon todo: decorator necessary?
    }.flatten

    return @slices
  end

  def export
    @dashboard = Dashboard.published.find(params[:id])
    @filename = "#{@dashboard.name} dashboard.csv"
  end
end

app/views/dashboards/_kpi-widget.html.erb
<%
  # usage at dashboard#show
%>
<div class="D1_kpi-group <%= widget.has_current_data? ? 'has-data' : 'has-no-data'; %>" data-id="<%= widget.id %>">
  <div class="widget <%= widget.name_slug %> <%= widget.style %>">
    <div id="<%= widget.name_slug %>" data-id="<%= widget.id %>" class="widget__title">
      <h2><%= widget.name %></h2>
      <a href="#dashboard-notes" title="View KPI <%= widget.name %> definition" class="fa fa-question-circle info" ga-on="click" ga-event-category="<%= GA::CATEGORY_SEEK_MORE_INFO %>" ga-event-action="<%= GA::ACTION_CLICK %>" ga-event-label="Hero title - <%= widget.name %>"><span class="sr-only"><%= widget.name %> definition</span></a>
      <div class="meta-group">
        <time class="widget__last-updated">Last updated <%= widget.last_updated_at %></time>
      </div>
      <div class="meta-group">
        <% if widget.show_description? %>
          <div class="widget__definition">
            <span class="widget__definition--title" aria-describedby="tooltip--<%= widget.name_slug %>">What is this?</span>
            <div class="widget__definition--content" role="tooltip" id="tooltip--<%= widget.name_slug %>">
              <div class="widget__definition--content__inner">
                <%= widget.description %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
    <div data-data="<%= render partial: 'chart/widget', locals: { widget: widget } %>" aria-hidden="true" class="widget__inner <%= widget.type %> <%= widget.style %>">
    </div>
    <%= render :partial => 'data_table', :locals => { :widget => widget } %>
  </div>
</div>

app/views/dashboards/_notes.html.erb
<dl>
  <% dashboard.notes.each do |note| %>
    <dt><%= note['title'] %></dt>
    <dd><%== note['body'] %></dd>
    <% if note['list'] %>
      <ul style='margin-top:0'>
        <% note['list'].each do |item| %>
          <li><%= item %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</dl>

app/views/dashboards/_overview_widget.html.erb
<div class="D1_kpi-group <%= widget.has_current_data? ? 'has-data' : 'has-no-data'; %>" data-id="<%= widget.id %>">
  <div class="widget <%= widget.name_slug %> <%= widget.style %>">
    <div class="widget__title <%= widget.name_slug %>">
      <h4><%= widget.name %></h4>
    </div>
    <div class="widget__inner <%= widget.name_slug %>" data-data="<%= render partial: 'chart/widget', locals: { widget: widget } %>" aria-hidden="true">
    </div>
    <%= render :partial => 'data_table_summary', :locals => { :widget => widget } %>
  </div>
</div>

app/views/dashboards/index.html.erb
<%
  content_for :title, 'Performance Dashboard'
  content_for :description, 'Australian Government Performance Dashboards'
%>
<div class="container">

  <section class="row" aria-labelledby="dashboardsoverview">
    <div class="col-md-12">
      <h1 id="dashboardsoverview">Performance Dashboard overview</h1>
    </div>

    <div class="dashboards-intro col-md-8">
      <p>The Performance Dashboard makes data open and accessible by measuring the performance of Australian government services against the Digital Service Standard.</p>
      <p>This promotes government transparency and helps drive the ongoing improvement of government services &mdash; for all Australians.</p>
    </div>

    <div class="dashboards-intro-sec hidden-sm-down col-md-4">
      <div class="media">
        <div class="media-left">
          <span class="number-of-dashboards"><%= dashboards.size %></span>
        </div>
        <div class="media-body media-middle">
          <span>service<br />dashboards</span>
        </div>
      </div>
    </div>
  </section>

  <section class="metrics row">
    <div class="metric-overview col-sm-12 col-md-4">
      <p>There are four key performance indicators that government services are required to publish on the Performance Dashboard.</p>
    </div>
    <div class="metric-definitions col-md-8 col-sm-12">
      <div class="metric-definitions-inner">
        <div class="metric-definitions__metric user-satisfaction col-sm-12 col-md-3">
          <div class="widget__title">
            <h2>User satisfaction</h2>
          </div>
          <p>The overall satisfaction rate with the service.</p>
        </div>
        <div class="metric-definitions__metric cost-per-transaction col-sm-12 col-md-3">
          <div class="widget__title">
          <h2>Cost per transaction</h2>
          </div>
          <p>The estimated cost to government, per transaction, for administering the service.</p>
        </div>
        <div class="metric-definitions__metric digital-take-up col-sm-12 col-md-3">
          <div class="widget__title">
          <h2>Digital take-up</h2>
          </div>
          <p>The adoption rate for the digital service.</p>
        </div>
        <div class="metric-definitions__metric completion-rate col-sm-12 col-md-3">
          <div class="widget__title">
          <h2>Completion rate</h2>
          </div>
          <p>The overall rate of completion for users of the service.</p>
        </div>
      </div>
      <div class="metric-link">
        <a href="https://www.dto.gov.au/standard/11-measure-performance/" rel="external" class="link--external-alt" target="_blank">Learn more about these key metrics</a>
      </div>
    </div>
    <div class="dashboards-intro-sec hidden-md-up col-sm-12">
      <div class="media">
        <div class="media-left">
          <span class="number-of-dashboards"><%= dashboards.size %></span>
        </div>
        <div class="media-body media-middle">
          <span>service<br />dashboards</span>
        </div>
      </div>
    </div>
  </section>


  <section aria-labelledby="servicedashboards">
    <h2 id="servicedashboards" class="dashboards-heading hidden-sm-down">Service dashboards</h2>
    <ul class="list-unstyled clearfix">
      <% dashboards.each do |dashboard| %>
        <li class="card row-deprecated-dont-add-this-anywhere-else">
          <div class="card__left">
            <div>
              <h3 class="card-title">
                <%= dashboard.dashboardized_name %>
              </h3>
              <div class="updated-at hidden-md-up">
                <time>Last updated on <%= dashboard.last_updated_at %></time>
              </div>
            </div>
            <div class="updated-at hidden-sm-down">
              <time>Last updated on <%= dashboard.last_updated_at %></time>
            </div>
            <%= link_to "View dashboard<span class='sr-only'> #{dashboard.name}</span>".html_safe, dashboard_path(dashboard), class: 'card__link__visible' %>
          </div>

          <% if dashboard.display_kpis? %>
              <div class="card__right dashboard__kpis clearfix">

                <% dashboard.widgets.kpis.by_pos.each do |widget| %>
                    <div class="aus-width-one-fourth">
                      <%= render :partial => 'overview_widget', :locals => { :dashboard => dashboard, :widget => widget.decorate } %>
                    </div>
                <% end %>

              </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </section>

</div>

app/views/dashboards/show.html.erb
<%
  content_for :title, dashboard.name
  content_for :description, dashboard.name
%>

<script>
  window.__STATE__ = <%== render(template: "/dashboards/show.json.jbuilder") %>;
</script>

<div>
  <div id="dashboard-show-app">
    <div class="hero-region">
      <div class="container">
        <div class="row">
          <div class="col-xs-12">
            <div class="D-loading-panel">
              <span>Loading...</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="below-the-line-bg">
    <div class="container">
      <div class="row">
        <div class="col-xs-12">
          <div class="D_widget-card widget dashboard-information">
            <div class="row">
              <div class="col-xs-12 col-lg-7">
                <div class=" widget-text">
                  <div class="widget-text__inner">
                    <div class="widget__title">
                      <h4>Dashboard information</h4>
                    </div>

                    <div id="dashboard-notes" class="widget__body">
                      <% if dashboard.show_notes? %>
                        <%= render partial: 'notes', locals: { dashboard: dashboard } %>
                      <% else %>
                        <p>No information available.</p>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>

              <div class="col-xs-12 col-lg-5">
                <div class="widget-text__footer">
                  <ul>
                    <li>
                      <% if dashboard.show_url? %>
                        <a href="<%= dashboard.url %>" target="_blank" class="link--external-alt"> Visit <%= dashboard.url %></a>
                      <% end %>
                    </li>

                    <li>
                      <%= link_to export_dashboard_path(dashboard, :format => 'csv'), class: "link--external-alt" do %>
                        Download dashboard data as CSV
                      <% end %>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>